# fly.toml app configuration file generated for import-ev-or-not on 2023-10-24T21:50:12+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "import-ev-or-not"
primary_region = "arn"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
